# This is a TOML document.

title = "Sample Client Config"

[owner]
name = "Client"
version = 0.1


# ENV are stored on the server
#sabre_password == ENV
#sabre_username == ENV
#sabre_pcc      == ENV
[sessions]
sabre_url = "https://webservices.sabre.com/websvc/"
    [sessions.client]
    url = "www.z.com"
    pool_size = 10

    [sessions.expire]
    # min/max are in minutes
    min = 10
    max = 28